#!/usr/bin/env python3
"""Regenerate expected_codes.lua from the test seed.

Usage:  python gen_expected.py > expected_codes.lua

Update SEED_BASE_EPOCH / SEED_SECRET if the TEST_SEED_ON_BOOT
fixture in src/storage.c changes.
"""
import base64
import hmac
import hashlib
import struct
import sys

SEED_BASE_EPOCH = 1778088090            # 2026-05-06 17:21:30 UTC
SEED_SECRET     = "JBSWY3DPEHPK3PXP"    # base32 ("Hello!\xDE\xAD\xBE\xEF")
WINDOWS         = 720                   # 6 hours of 30s windows


def totp(t: int, key: bytes) -> int:
    T   = t // 30
    msg = struct.pack(">Q", T)
    mac = hmac.new(key, msg, hashlib.sha1).digest()
    o   = mac[19] & 0x0F
    return struct.unpack(">I", mac[o:o + 4])[0] & 0x7FFFFFFF


def main() -> None:
    key = base64.b32decode(SEED_SECRET)
    out = sys.stdout.write
    out("-- Auto-generated by tests/gen_expected.py\n")
    out(f"-- secret    = {SEED_SECRET}\n")
    out(f"-- base epoch= {SEED_BASE_EPOCH}\n")
    out(f"-- {WINDOWS} entries = {WINDOWS * 30 // 3600}h of 30s windows\n")
    out("return {\n")
    for i in range(WINDOWS):
        t    = SEED_BASE_EPOCH + i * 30
        code = totp(t, key) % 1_000_000
        out(f"    [{i}] = {code},\n")
    out("}\n")


if __name__ == "__main__":
    main()
